# Error Handling

C√°c ph·∫ßn tr∆∞·ªõc th√¨ to√†n b·ªô ƒë·ªÅu x·ª≠ l√Ω th√†nh c√¥ng. Ch∆∞a c√≥ tr∆∞·ªùng h·ª£p n√†o l·ªói hay subscription m√† nh·∫≠n ƒë∆∞·ª£c complete l√† error. Ph·∫ßn n√†y s·∫Ω gi·∫£i quy·∫øt h·∫øt cho b·∫°n.

Tr∆∞·ªõc ti√™n th√¨ quan t√¢m l·∫°i ch·ªó c√∫ ph√°p c·ªßa 1 Publisher nh∆∞ th·∫ø n√†o:

> Publisher < Output, Failure >

Gi·ªù chuy·ªÉn h∆∞·ªõng t·∫•n c√¥ng sang `Failure` n√†o!

## 11.1. Never

### Never

N·∫øu type c·ªßa Failure l√† `Never` th√¨ publisher c·ªßa b·∫°n kh√¥ng bao gi·ªù l·ªói. B·∫°n mu·ªën d·ª´ng l·∫°i publisher ƒë√≥ khi n√†o g·ªçi completion successfully.

V√≠ d·ª•:

```swift
Just("Hello")
    .sink(receiveValue: { print($0) })
    .store(in: &subscriptions)
```

C√≥ g√¨ kh√°c l·∫° ·ªü ƒë√¢y kh√¥ng n√†o?

> Combine + Xcode n√≥ th√¥ng minh, s·∫Ω suggestion b·∫°n `sink` ch·ªâ nh·∫≠n value th√¥i. V√¨ ko c√≥ l·ªói.

### `setFailureType`

ƒê·ªÉ th√™m type cho `Failure` th√¨ b·∫°n d√πng to√°n t·ª≠ `setTypeFailure`. Xem code v√≠ d·ª• cho Just tr√™n.

```swift
Just("Hello")
    .setFailureType(to: MyError.self)
    .sink(receiveCompletion: { completion in
      
      switch completion {
      case .failure(.ahihi):
        print("Finished with Oh No!")
      case .finished:
        print("Finished successfully!")
      }
      
    }, receiveValue: { value in
      print("Got value: \(value)")
    })
    .store(in: &subscriptions)
```

L√∫c n√†y n√™n b·∫°n d√πng `sink` cho Just th√¨ s·∫Ω ph·∫£i s·ª≠ d·ª•ng function v·ªõi phi√™n b·∫£n ƒë·∫ßy ƒë·ªß cho completion v√† value nh·∫≠n ƒë∆∞·ª£c.

###  `assign(to:on:)`

ƒê√¢y l√† c√°ch ƒë·ªÉ subscribe t·ªõi 1 publisher nh∆∞ng gi√° tr·ªã s·∫Ω ƒë∆∞·ª£c ƒë·∫©y th·∫≥ng v·ªÅ 1 property c·ªßa 1 ƒë·ªëi t∆∞·ª£ng. C√°i n√†y c≈©ng s·ª≠ d·ª•ng cho tr∆∞·ªùng h·ª£p kh√¥ng bao gi·ªù l·ªói.

```swift
// 1
  class Person {
    let id = UUID()
    var name = "Unknown"
  }

  // 2
  let person = Person()
  print("1", person.name)

  Just("Shai")
    .handleEvents( // 3
      receiveCompletion: { _ in print("2", person.name) }
    )
    .assign(to: \.name, on: person) // 4
    .store(in: &subscriptions)
```

Trong ƒë√≥:

1. ƒê·ªãnh nghƒ©a class
2. T·∫°o ƒë·ªëi t∆∞·ª£ng
3. Nh·∫≠n s·ª± ki·ªán v·ªõi completion. Do assign th√¨ ko bi·∫øt l√∫c n√†o n√≥ k·∫øt th√∫c
4. assign g√≠a tr·ªã t·ªõi property name c·ªßa ƒë·ªëi t∆∞·ª£ng

### `assertNoFailure`

M·ªôt pha b·∫ª l√°i n·ªØa t·ªõi t·ª´ Combine. N·∫øu b·∫°n mu·ªën b·∫£o v·ªá publisher c·ªßa m√¨nh v√† ƒë·∫£m b·∫£o r·∫±ng n√≥ kh√¥ng th·ªÉ fail th√¨ s·ª≠ d·ª•ng to√°n t·ª≠ `assertNoFailure`. 

Kh√° bu·ªìn l√† n√≥ kh√¥ng ngƒÉn ch·∫∑n ƒë∆∞·ª£c failure t·ª´ publisher, nh∆∞ng b√π l·∫°i n√≥ g√¢y `crash` cho ch∆∞∆°ng tr√¨nh b·∫±ng `fatalError`. Mo√°, th√¢m v√£i n·ªìi!

```swift
Just("Hello")
    .setFailureType(to: MyError.self)
    //.tryMap { _ in throw MyError.ahihi }
    .assertNoFailure() // 2
    .sink(receiveValue: { print("Got value: \($0) ")}) // 3
    .store(in: &subscriptions)
```

V√† khi c·ªë g·∫Øng ti·∫øp t·ª•c v·ªõi `tryMap` ƒë·ªÉ n√©m l·ªói ra l·∫°i th√¨ ch∆∞∆°ng tr√¨nh s·∫Ω crash. V√¨ n√≥ ƒë√£ ƒë∆∞·ª£c nh·∫≠n khai b√°o l√† kh√¥ng bao gi·ªù l·ªói n·ªØa.

> M·ª£t m·ªèi v·ªõi t·ª•i n√†y qu√°. Gi·ªù sang ph·∫ßn ch√≠nh th√¥i

## 11.2. Dealing with failure

### try* Operators

ƒê√¢y l√† c√°c to√°n t·ª≠ b·∫Øt ƒë·∫ßu v·ªõi t·ª´ kho√° `try` .Kh√° l√† th√∫ v·ªã, nh∆∞ng c√≥ th·ªÉ gi·∫£i quy·∫øt 1 th√®n `tryMap` tr∆∞·ªõc. C√°c th√®n kh√°c t∆∞∆°ng t·ª±. C≈©ng v√¨ c√°c to√°n t·ª≠ n√†y th∆∞·ªùng n√©m ƒëi ra 1 error.

Xem v√≠ d·ª• cho c·∫£ 2

```swift
// define error 
enum NameError: Error {
    case tooShort(String)
    case unknown
  }
  
 // publisher
  let names = ["Scott", "Marin", "Shai", "Florent"].publisher
  
  // map
  names
    .map { value in
      return value.count
   }
  .sink(receiveCompletion: { print("üîµ Completed with \($0)") }, 
        receiveValue: { print("üîµ Got Value: \($0)") })
  .store(in: &subscriptions)
  
  // tryMap
  names
    .tryMap { value -> Int in
      
      let length = value.count
      
      guard length >= 5 else { throw NameError.tooShort(value) }
      
      return value.count
   }
  .sink(receiveCompletion: { print("üî¥ Completed with \($0)") }, 
        receiveValue: { print("üî¥Got Value: \($0)") })
  .store(in: &subscriptions)
```

### `mapError`

Ch√∫ng ta b·∫Øt ƒë·∫ßu nh∆∞ sau:

```swift
enum NameError: Error {
    case tooShort(String)
    case unknown
  }
  
  Just("Hello")
    .setFailureType(to: NameError.self)
    .map { $0 + " World!" }
    .sink(receiveCompletion: { completion in
      
      switch completion {
      case .finished:
        print("Done!")
      case .failure(.tooShort(let name)):
        print("\(name) is too short!")
      case .failure(.unknown):
          print("An unknown name error occurred")
      }
      
    }, receiveValue: { print("Got value \($0)") })
    .store(in: &subscriptions)
```

Kh√¥ng c√≥ g√¨ kh√≥ hi·ªÉu ·ªü ƒë√¢y h·∫øt. C√°c error ƒë·ªÅu ƒë∆∞·ª£c b·∫Øt ·ªü completion. C√≥ ƒëi·ªÅu b·∫°n ch√∫ √Ω th√¨ ki·ªÉu c·ªßa completion l√∫c n√†y l√†:

```swift
let completion: Subscribers.Completion<NameError>
```

N√≥ ch·ªâ ƒë√≠ch danh t·ªõi `NameError`. OKE, gi·ªù ta ƒë·ªïi t·ª´ `map` th√†nh `tryMap`.

```swift
Just("Hello")
    .setFailureType(to: NameError.self)
    //.map { $0 + " World!" }
    .tryMap { throw NameError.tooShort($0) }
    .sink(receiveCompletion: { completion in
      
      switch completion {
      case .finished:
        print("Done!")
      case .failure(.tooShort(let name)):
        print("\(name) is too short!")
      case .failure(.unknown):
          print("An unknown name error occurred")
      }
      
    }, receiveValue: { print("Got value \($0)") })
    .store(in: &subscriptions)
```

L√∫c n√†y th√¨ xu·∫•t hi·ªán l·ªói ·ªü tr√¨nh bi√™n d·ªãch. V√¨ ki·ªÉu c·ªßa completion l√∫c n√†y ƒë√£ kh√°c r·ªìi.

```swift
let completion: Subscribers.Completion<Error>
```

Nh∆∞ v·∫≠y n√≥ s·∫Ω quy c√°c l·ªói v·ªÅ l·ªói chung chung c·ªßa Swift. ƒêi·ªÅu n√†y ki·∫øn ch√∫ng ta ph·∫£i m·ªát m·ªèi trong vi·ªác x√°c ƒë·ªãnh r√µ l·ªói thu·ªôc lo·∫°i g√¨ v√† ·ªü ƒë√¢u?

Gi·∫£i quy·∫øt ti·∫øp v·ªõi to√°n t·ª≠ `mapError`.

```swift
Just("Hello")
    .setFailureType(to: NameError.self)
    //.map { $0 + " World!" }
    .tryMap { throw NameError.tooShort($0) }
    .mapError { $0 as? NameError ?? .unknown }
    .sink(receiveCompletion: { completion in
      
      switch completion {
      case .finished:
        print("Done!")
      case .failure(.tooShort(let name)):
        print("\(name) is too short!")
      case .failure(.unknown):
          print("An unknown name error occurred")
      }
      
    }, receiveValue: { print("Got value \($0)") })
    .store(in: &subscriptions)
```

OKE, m·ªçi vi·ªác l·∫°i ho·∫°t ƒë·ªông ·ªïn ƒë·ªãnh. Qua ƒë√¢y ta th·∫•y ƒë∆∞·ª£c `mapError` s·∫Ω:

* b·∫Øt c√°c error ph√°t ra
* bi·∫øn ƒë·ªïi n√≥ v·ªÅ th√†nh 1 ki·ªÉu ch·ªâ ƒë·ªãnh n√†o ƒë√≥
* c√≥ th·ªÉ √©p ki·ªÉu c·ªßa c·∫£ error

## 11.3. **Designing your fallible APIs**

Ch√∫ng ta s·∫Ω b·∫Øt ƒë·∫ßu b·∫±ng code c·ªßa 1 class kh√° d√†i cho vi·ªác handle api v·ªõi error

```swift
 class DadJokes {
  struct Joke: Codable {
    let id: String
    let joke: String
  }
  
  enum Error: Swift.Error, CustomStringConvertible {
    case network
    case jokeDoesntExist(id: String)
    case parsing
    case unknown

    var description: String {
      switch self {
      case .network:
        return "Request to API Server failed"
      case .parsing:
        return "Failed parsing response from server"
      case .jokeDoesntExist(let id):
        return "Joke with ID \(id) doesn't exist"
      case .unknown:
        return "An unknown error occurred"
      }
    }
  }
    
    // call api
    func getJoke(id: String) -> AnyPublisher<Joke, Error> {
      guard id.rangeOfCharacter(from: .letters) != nil else {
        return Fail<Joke, Error>(error: .jokeDoesntExist(id: id))
                .eraseToAnyPublisher()
      }
      
      let url = URL(string: "https://icanhazdadjoke.com/j/\(id)")!
      var request = URLRequest(url: url)
      request.allHTTPHeaderFields = ["Accept": "application/json"]
      
      return URLSession.shared
        .dataTaskPublisher(for: request)
      //.map(\.data)
        .tryMap { data, _ -> Data in
          guard let obj = try? JSONSerialization.jsonObject(with: data),
                let dict = obj as? [String: Any],
                dict["status"] as? Int == 404 else {
            return data
          }
          throw DadJokes.Error.jokeDoesntExist(id: id)
        }
        .decode(type: Joke.self, decoder: JSONDecoder())
        .mapError { error -> DadJokes.Error in
          switch error {
          case is URLError:
            return .network
          case is DecodingError:
            return .parsing
          default:
            return error as? DadJokes.Error ?? .unknown
          }
        }
        .eraseToAnyPublisher()
    }
    
  }
```

Trong ƒë√≥ ph·∫ßn define

* struct `joker` ƒë·ªÉ define d·ªØ li·ªáu cho ƒë·ªëi t∆∞·ª£ng s·∫Ω d√πng parse data tr·∫£ v·ªÅ
* enum `Error` ƒë·ªÉ ƒë·ªãnh nghƒ©a c√°c tr∆∞·ªùng h·ª£p error (c·∫£ chung l·∫´n ri√™ng)
* `CustomStringConvertible` gi√∫p cho vi·ªác s·ª≠ d·ª•ng th√¢n thi·ªán error v·ªõi `description`

```swift
func getJoke(id: String) -> AnyPublisher<Joke, Error> { ... }
```

function ch√≠nh g·ªçi API v√† tr·∫£ v·ªÅ error. Ph·∫ßn ƒë·∫ßu l√† t·∫°o request t·ª´ URL. Trong ƒë√≥ √Ω nghƒ©a c√°c to√°n t·ª≠ nh∆∞ sau:

* `dataTaskPublisher` bi·∫øn vi·ªác t∆∞∆°ng t√°c ƒë√≥ th√†nh publisher
* `map()` ƒë·ªÉ l·∫•y ph·∫ßn data. Tuy nhi√™n v·ªõi to√°n t·ª≠ n√†y th√¨ m√¨nh s·∫Ω kh√¥ng th·∫•y ƒë∆∞·ª£c l·ªói.
* `decode` s·∫Ω parse data th√†nh ki·ªÉu m√¨nh mu·ªën th√¥ng qua JSONDecoder
* `mapError` s·∫Ω b·∫Øt l·ªói, bi·∫øn l·ªói th√†nh k·ªÉu m√¨nh mong mu·ªën ƒë·ªÉ d·ªÖ qu·∫£n l√Ω. V√¨ l·ªói c√≥ th·ªÉ do nhi·ªÅu nguy√™n nh√¢n
  * URL
  * Connect th·∫•t b·∫°i
  * Parse JSON th·∫•t b·∫°i
  * Ho·∫∑c chung chung
* `eraseToAnyPublisher` xo√° s·∫°ch d·∫•u v·∫øt
* `tryMap` m·ªôt s·ªë c√¥ng vi·ªác s·∫Ω c√≥ l·ªói nh∆∞ parse JSON, n√™n s·ª≠ d·ª•ng to√°n t·ª≠ n√†y. Ngo√†i ra, c√≤n b·∫Øt tr∆∞·ªõc m·ªôt s·ªë l·ªói n·ªØa, nh∆∞ b√†i v√≠ d·ª• l√† `status_code`
* `Fail` d√πng ƒë·ªÉ t·∫°o ra 1 publisher m√† n√©m ƒëi `failure`

S·ª≠ d·ª•ng nh∆∞ b√¨nh th∆∞·ªùng

```swift
let api = DadJokes()
  let jokeID = "9prWnjyImyd"
  let badJokeID = "123456"
  // 5
  api
    .getJoke(id: badJokeID)
    .sink(receiveCompletion: { print($0) },
          receiveValue: { print("Got joke: \($0)") })
    .store(in: &subscriptions)
```

Ho√°n v·ªã 2 c√°i `jokeID` v√† `badJokeID` ƒë·ªÉ xem k·∫øt qu·∫£.

## 11.4. retrying & catching

Gi·ªù t·ªõi l√∫c x·ª≠ l√Ω t·ªïng h·ª£p r·ªìi. N·∫øu nh∆∞ t∆∞∆°ng t√°c v·ªõi API c·ªßa b·∫°n th·∫≠t b·∫°i. Nh∆∞ng b·∫°n v·∫´n mu·ªën c·ªë g·∫Øng n√≠u k√©o th√™m v√†i l·∫ßn n·ªØa. V√† th·ª±c hi·ªán vi·ªác `call request` th√¨ to√°n t·ª≠ `retry`  s·∫Ω gi√∫p b·∫°n.

Ch√∫ng ta theo d√µi ƒëo·∫°n code sau, gi·∫£ s·ª≠ c√≥ 1 l·ªõp `PhotoService`

```swift
let photoService = PhotoService()

photoService
    .fetchPhoto(quality: .high)
    .handleEvents(
      receiveSubscription: { _ in print("Trying ...") },
      receiveCompletion: {
        guard case .failure(let error) = $0 else { return }
        print("Got error: \(error)")
      }
    )
    .retry(3)
    .catch { error -> PhotoService.Publisher in
      print("Failed fetching high quality, falling back to low quality")
      return photoService.fetchPhoto(quality: .low)
    }
    .replaceError(with: UIImage(named: "na.jpg")!)
    .sink(
      receiveCompletion: { print("\($0)") },
      receiveValue: { image in
        image
        print("Got image: \(image)")
      }
    )
    .store(in: &subscriptions)
```

Function `fetchPhoto(quality: .high)` c·ªßa n√≥ s·∫Ω cho ph√©p m√¨nh custom v·ªõi ch·∫•t l∆∞·ª£ng b·ª©c ·∫£nh. V·ªõi ch·∫•t l∆∞·ª£ng cao th√¨ s·∫Ω failed. Khi ƒë√≥ s·∫Ω ti·∫øn h√†nh:

* `handleEvents` -> `receiveCompletion` = `failur`e : ƒë·ªÉ th√¥ng b√°o ng∆∞·ªùi d√πng bi·∫øt
* `.retry(3)` th·ª≠ l·∫°i 3 l·∫ßn

N·∫øu nh∆∞ c·∫£ 3 l·∫ßn th·∫•t b·∫°i v·ªõi ch·∫•t l∆∞·ª£ng cao, th√¨ ch·ªët ch·∫∑n ti·∫øp theo l√† `catch` error v√† ti·∫øn h√†nh th·ª≠ l·∫°i v·ªõi ch·∫•t l∆∞·ª£ng th·∫•p.

N·∫øu nh∆∞ t·ªõi c·∫£ ch·∫•t l∆∞·ª£ng th·∫•t m√† th·∫•t b·∫°i ti·∫øp n·ªØa th√¨ ch·ªët ch·∫∑n cu·ªëi c√πng l√† `replaceError` v·ªõi 1 c√°i ·∫£nh m·∫∑c ƒë·ªãnh. ƒêi·ªÅu n√†y c√≥ √Ω nghƒ©a trong ng·ªØ c·∫£nh UI, v√¨ giao di·ªán ng∆∞·ªùi d√πng kh√¥ng th·ªÉ fail hay ko hi·ªÉn th·ªã g√¨ h·∫øt. N√™n ƒë·ªëi v·ªõi b·∫°n th√¨ ph·∫£i tu·ª≥ thu·ªôc v√†o y√™u c·∫ßu b√†i to√°n ƒë·ªÉ x·ª≠ l√Ω cho ƒë·∫πp.

> OKE, ƒë√≥ l√† c√°c b∆∞·ªõc c∆° b·∫£n ƒë·ªÉ x·ª≠ l√Ω Error.

## T√≥m t·∫Øt

* `Never` ki·ªÉu c·ªßa Failure ƒë·ªÉ publisher kh√¥ng bao gi·ªù th·∫•t b·∫°i
* C√°c to√°n t·ª≠ thay ƒë·ªïi thu·ªôc t√≠nh
  * `setFailureType` th√™m type cho Failure, khi mu·ªën bi·∫øn thanh ni√™n n√†o Never th√¨ ko Never
  * `assertNoFailure` kh·∫≥ng ƒë·ªãnh ko c√≥ l·ªói, d√†nh cho c√°c thanh ni√™n publisher c√≥ khai b√°i t·ª´ tr∆∞·ªõc.
* Ki·ªÉu subscribe
  * `sink` d√†nh cho c√≥ Failure
  * `assign` d√†nh cho Never
* V·ªõi c√°c lo·∫°i to√°n t·ª≠ c√≥ t·ª´ kho√° ƒë·∫ßu ti√™n l√† `try` th√¨ ph·∫£i c·ªë g·∫Øng n√©m ra `throw`  error
* C√°c error m√† ko ƒëc `throw` ra th√¨ cho v·ªÅ lo·∫°i chung chung `Swift.Error`. Th∆∞·ªùng s·∫Ω ph√°t sinh ra khi d√πng to√°n t·ª≠ `try`
* `mapError` d√πng ƒë·ªÉ x·ª≠ l√Ω error ph√°t sinh
  * Bi·∫øn ƒë·ªïi v·ªÅ ki·ªÉu Error m√† m√¨nh ƒë·ªãnh nghƒ©a
  * Log ra ho·∫∑c √©p ki·ªÉu v·ªÅ Error c·ªßa m√¨nh
  * C√≥ th·ªÉ g·ªçi l·∫°i m·ªôt s·ªë function kh√°c ƒë·ªÉ x·ª≠ l√Ω th√™m
* N√™n define type Error ri√™ng ƒë·ªÉ b·ªçc lu√¥n c√°c l·ªói c·ªßa publisher, h·ªá th·ªëng ...
* `retry(:)` ƒë·ªÉ subscribe l·∫°i khi nh·∫≠n ƒëc failure c·ªßa publisher
* `replaceError(with:)` ƒë·ªÉ l√† ch·ªët ch·∫∑n cu·ªëi c√πng, khi mu·ªën thay th·ªÉ error b·∫±ng gi√° tr·ªã m·∫∑c ƒë·ªãnh n√†o ƒë√≥
* `catch` ƒë·ªÉ b·∫Øt error v√† b·∫ª l√°i sang h∆∞·ªõng kh√°c

---

## H·∫æT

